# -*- coding: utf-8 -*-
"""Pilot_analysis_employee_churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HyuKBEfspp_PPT1UdqUu5uC2ZZHg0I9O
"""



"""#connect to big query"""

#libraries that we need
from google.cloud import bigquery
from google.colab import auth

#authenicate
auth.authenticate_user()

# initialize the client for BigQuery
project_id = "hale-life-398519"
client = bigquery.Client(project=project_id, location= 'US')

#Get the dataset and table
dataset_ref  = client.dataset("EmployeeChurn",project=project_id)
dataset = client.get_dataset(dataset_ref)
table_ref = dataset.table('tbl_hr_data')
table = client.get_table(table_ref)
table.schema

nw_table_ref = dataset.table('new_employee')
new_table = client.get_table(nw_table_ref)
new_table.schema

# convert to dataframe
df=client.list_rows(table=table).to_dataframe()
df.head()

# convert to dataframe
df2 =client.list_rows(table=new_table).to_dataframe()
df2.head()

"""# build model
### install Pycaret
"""

#install pycaret
!pip install pycaret

"""# code and train model"""

# get our model
from pycaret.classification import *

# setup our model
setup(df, target='Quit_the_Company', session_id=123,ignore_features= ['employee_id'],categorical_features=['salary','Departments'])

compare_models()

rf_model = create_model('rf')

final_df = predict_model(rf_model)

final_df.head()

new_predictions = predict_model(rf_model,data=df2,raw_score=True)

new_predictions.head()

new_predictions.to_gbq(destination_table='EmployeeChurn.new_predictions',
                       project_id=project_id,chunksize=None,if_exists='replace')
#

plot_model(rf_model,plot='feature')

# create a feature table
rf_model.feature_names_in_

rf_model.feature_importances_

import pandas as pd
feature_table = pd.DataFrame(zip(rf_model.feature_names_in_,rf_model.feature_importances_),columns=['feature','importance'])
feature_table

feature_table.to_gbq(destination_table='EmployeeChurn.feature_table',
                       project_id=project_id,chunksize=None,if_exists='replace')